#!/bin/bash

# Variables
CERT_PATH="$HOME/autosigned.crt"
KEY_PATH="$HOME/autosigned.key"

# Création du certificat auto-signé sans dns 
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${KEY_PATH} -out ${CERT_PATH} -subj "/C=FR/ST=State/L=City/O=Organization/CN="


# Afficher le certificat généré
cat ${CERT_PATH}

# Afficher la clé privée générée
cat ${KEY_PATH}
