#!/bin/bash

# Installation openssl 
sudo apt install openssl

# Variables
CERT_PATH="/etc/ssl/autosigned.crt"
KEY_PATH="/etc/ssl/autosigned.key"

# Création du certificat auto-signé sans dns 
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${KEY_PATH} -out ${CERT_PATH} -subj "/C=FR/ST=State/L=City/O=Organization/CN="


# Afficher le certificat généré
sudo cat ${CERT_PATH}

# Afficher la clé privée générée
sudo cat ${KEY_PATH}
